Repository palantir/conjure-java-runtime, pull requests merged in 2019-09, with the labels that each got.

#1203 Upgrade jackson-databind to 2.9.9.3 from 2.9.9
  changelog/@unreleased/pr-1203.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#1205 Completely revamp tracing spans
  changelog/@unreleased/pr-1205.v2.yml
  conjure-java-jaxrs-client/build.gradle
  conjure-java-jaxrs-client/src/main/java/com/palantir/conjure/java/client/jaxrs/feignimpl/NeverReturnNullDecoder.java
  conjure-java-jaxrs-client/src/main/java/com/palantir/conjure/java/client/jaxrs/feignimpl/PathTemplateHeaderEnrichmentContract.java
  conjure-java-jaxrs-client/src/test/java/com/palantir/conjure/java/client/jaxrs/TracerTest.java
  conjure-java-retrofit2-client/build.gradle
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/TestService.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/TracerTest.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/ConcurrencyLimiters.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/DispatcherTraceTerminatingInterceptor.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/OkHttpClients.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/OkhttpTraceInterceptor.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpCall.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpClient.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/SpanTerminatingInterceptor.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/Tags.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#1249 remove hamcrest conditions
  conjure-java-jaxrs-client/src/test/java/com/palantir/conjure/java/client/jaxrs/JaxRsClientFailoverTest.java
  conjure-java-jaxrs-client/src/test/java/com/palantir/conjure/java/client/jaxrs/JaxRsClientGuavaOptionalHandlingTest.java
  conjure-java-jaxrs-client/src/test/java/com/palantir/conjure/java/client/jaxrs/JaxRsClientJava8OptionalHandlingTest.java
  conjure-java-jaxrs-client/src/test/java/com/palantir/conjure/java/client/jaxrs/TracerTest.java
  conjure-java-jaxrs-client/src/test/java/com/palantir/conjure/java/client/jaxrs/feignimpl/GuavaOptionalAwareDecoderTest.java
  conjure-java-jaxrs-client/src/test/java/com/palantir/conjure/java/client/jaxrs/feignimpl/HeaderAccessUtilsTest.java
  conjure-java-jaxrs-client/src/test/java/com/palantir/conjure/java/client/jaxrs/feignimpl/InputStreamDelegateDecoderTest.java
  conjure-java-jaxrs-client/src/test/java/com/palantir/conjure/java/client/jaxrs/feignimpl/InputStreamDelegateEncoderTest.java
  conjure-java-jaxrs-client/src/test/java/com/palantir/conjure/java/client/jaxrs/feignimpl/Java8OptionalAwareDecoderTest.java
  conjure-java-jaxrs-client/src/test/java/com/palantir/conjure/java/client/jaxrs/feignimpl/SlashEncodingContractTest.java
  conjure-java-jaxrs-client/src/test/java/com/palantir/conjure/java/client/jaxrs/feignimpl/TextDelegateDecoderTest.java
  conjure-java-jaxrs-client/src/test/java/com/palantir/conjure/java/client/jaxrs/feignimpl/TextEncoderTest.java
  conjure-java-jaxrs-client/src/test/java/com/palantir/conjure/java/client/jaxrs/feignimpl/UserAgentTest.java
  conjure-java-jersey-server/src/test/java/com/palantir/conjure/java/server/jersey/DateTimeTest.java
  conjure-java-jersey-server/src/test/java/com/palantir/conjure/java/server/jersey/ExceptionMappingTest.java
  conjure-java-jersey-server/src/test/java/com/palantir/conjure/java/server/jersey/GuavaOptionalTest.java
  conjure-java-jersey-server/src/test/java/com/palantir/conjure/java/server/jersey/Java8OptionalTest.java
  conjure-java-jersey-server/src/test/java/com/palantir/conjure/java/server/jersey/StringFormatTest.java
  conjure-java-jersey-server/src/test/java/com/palantir/conjure/java/server/jersey/TracerTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2ClientBuilderTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2ClientProxyTest.java
  keystores/src/test/java/com/palantir/conjure/java/config/ssl/DropwizardSslClientAuthTests.java
  keystores/src/test/java/com/palantir/conjure/java/config/ssl/KeyStoresTests.java
  keystores/src/test/java/com/palantir/conjure/java/config/ssl/SerializationTests.java
  keystores/src/test/java/com/palantir/conjure/java/config/ssl/SslSocketFactoriesConnectionTests.java
  keystores/src/test/java/com/palantir/conjure/java/config/ssl/SslSocketFactoriesTests.java
  keystores/src/test/java/com/palantir/conjure/java/config/ssl/pkcs1/Pkcs1ReadersTests.java
  pkcs1-reader-bouncy-castle/src/test/java/com/palantir/conjure/java/config/ssl/pkcs1/BouncyCastlePkcs1ReaderTests.java
  pkcs1-reader-sun/src/test/java/com/palantir/conjure/java/config/ssl/pkcs1/SunPkcs1ReaderTests.java
Labels: merge when ready, no changelog

#1257 Only apply stalebot to PRs (not issues)
  .github/stale.yml
Labels: no changelog

#1254 Fix: Prevent NPEs for clients created from newBuilder()
  changelog/@unreleased/pr-1254.v2.yml
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/OkhttpTraceInterceptor.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/SpanTerminatingInterceptor.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/OkHttpClientsTest.java
Labels: autorelease, merge when ready

#1256 okhttp clients sets SO_KEEPALIVE
  changelog/@unreleased/pr-1256.v2.yml
  client-config/src/main/java/com/palantir/conjure/java/client/config/ClientConfigurations.java
  client-config/src/main/java/com/palantir/conjure/java/client/config/ForwardingSslSocketFactory.java
  client-config/src/main/java/com/palantir/conjure/java/client/config/KeepAliveSslSocketFactory.java
  client-config/src/test/java/com/palantir/conjure/java/client/config/ClientConfigurationsTest.java
Labels: autorelease, merge when ready

#1262 Separate QoS responses in host metrics
  changelog/@unreleased/pr-1262.v2.yml
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/DefaultHostMetrics.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/HostMetrics.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/HostMetricsTest.java
  readme.md
Labels: merge when ready
