Repository palantir/conjure-java-runtime, pull requests merged in 2019-10, with the labels that each got.

#1267 Accept revapi break
  .palantir/revapi.yml
  build.gradle
Labels: merge when ready, no changelog

#1266 Add KeepAliveSslSocketFactory wrapper to the other ClientConfigurations.of()
  changelog/@unreleased/pr-1266.v2.yml
  client-config/src/main/java/com/palantir/conjure/java/client/config/ClientConfigurations.java
  client-config/src/test/java/com/palantir/conjure/java/client/config/ClientConfigurationsTest.java
Labels: autorelease, merge when ready

#1269 ClientConfiguration equality works again
  changelog/@unreleased/pr-1269.v2.yml
  client-config/src/main/java/com/palantir/conjure/java/client/config/KeepAliveSslSocketFactory.java
  client-config/src/test/java/com/palantir/conjure/java/client/config/ClientConfigurationsTest.java
Labels: merge when ready

#1291 Fix: Don't report outcome of canceled requests to HostEventSink
  changelog/@unreleased/pr-1291.v2.yml
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/InstrumentedInterceptor.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/InstrumentedInterceptorTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/OkHttpClientsTest.java
Labels: autorelease, merge when ready

#1298 Implement unknown remote exception
  changelog/@unreleased/pr-1298.v2.yml
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemoteExceptionResponseHandler.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpCall.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/UnknownRemoteExceptionResponseHandler.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/OkHttpClientsTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/UnknownRemoteExceptionResponseHandlerTest.java
Labels: merge when ready
