Repository palantir/conjure-java-runtime, pull requests merged in 2019-08, with the labels that each got.

#1171 Allow disabling of handling of SocketExceptions
  changelog/@unreleased/pr-1171.v2.yml
  client-config/src/main/java/com/palantir/conjure/java/client/config/ClientConfiguration.java
  client-config/src/main/java/com/palantir/conjure/java/client/config/ClientConfigurations.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/OkHttpClients.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpCall.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpClient.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/OkHttpClientsTest.java
Labels: autorelease, merge when ready

#1104 Test failed URLs before allowing them to be used again
  changelog/@unreleased/pr-1104.v2.yml
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/OkHttpClients.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpCall.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/UrlSelector.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/UrlSelectorImpl.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/OkHttpClientsTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/UrlSelectorImplTest.java
Labels: merge when ready

#1168 Handle null timeout messages
  changelog/@unreleased/pr-1168.v2.yml
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpCall.java
Labels: merge when ready

#1167 Increase the default parallel requests for clients
  changelog/@unreleased/pr-1167.v2.yml
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/OkHttpClients.java
Labels: merge when ready

#1183 Correctly handle Query Parameters for optional primitives
  changelog/@unreleased/pr-1183.v2.yml
  conjure-java-jersey-server/src/main/java/com/palantir/conjure/java/server/jersey/Java8OptionalDoubleParamConverterProvider.java
  conjure-java-jersey-server/src/main/java/com/palantir/conjure/java/server/jersey/Java8OptionalIntParamConverterProvider.java
  conjure-java-jersey-server/src/main/java/com/palantir/conjure/java/server/jersey/Java8OptionalLongParamConverterProvider.java
  conjure-java-jersey-server/src/test/java/com/palantir/conjure/java/server/jersey/Java8OptionalTest.java
Labels: autorelease, merge when ready

#1184 Fix: Convert retrofit optional Header parameters into string representation of wrapped objects
  changelog/@unreleased/pr-1184.v2.yml
  conjure-java-retrofit2-client/src/main/java/com/palantir/conjure/java/client/retrofit2/OptionalObjectToStringConverterFactory.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/OptionalObjectToStringConverterFactoryTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2ClientApiTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/TestService.java
Labels: autorelease, merge when ready

#1196 Don't potentially leak response bodies when cancelling Retrofit calls
  changelog/@unreleased/pr-1196.v2.yml
  conjure-java-retrofit2-client/src/main/java/com/palantir/conjure/java/client/retrofit2/AsyncSerializableErrorCallAdapterFactory.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/AsyncSerializableErrorCallAdapterFactoryTest.java
  conjure-java-retrofit2-client/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: autorelease, merge when ready

#1197 Deal with nit
  conjure-java-retrofit2-client/src/main/java/com/palantir/conjure/java/client/retrofit2/AsyncSerializableErrorCallAdapterFactory.java
Labels: merge when ready, no changelog
