Repository palantir/conjure-java-runtime, pull requests merged in 2020-01, with the labels that each got.

#1389 Respond with 401 when missing credentials
  changelog/@unreleased/pr-1389.v2.yml
  conjure-java-jersey-server/src/main/java/com/palantir/conjure/java/server/jersey/AuthHeaderParamConverterProvider.java
  conjure-java-jersey-server/src/main/java/com/palantir/conjure/java/server/jersey/BearerTokenParamConverterProvider.java
  conjure-java-jersey-server/src/test/java/com/palantir/conjure/java/server/jersey/AuthTest.java
Labels: autorelease, merge when ready

#1395 Add test demonstrating the deserialization behavior of JSON string body
  conjure-java-jersey-server/src/test/java/com/palantir/conjure/java/server/jersey/StringFormatTest.java
Labels: merge when ready, no changelog

#1391 General cleanup in RemotingOkHttpCall
  changelog/@unreleased/pr-1391.v2.yml
  okhttp-clients/build.gradle
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpCall.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpClient.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/OkHttpClientsRealServerTest.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#1399 Resolve OkHttpClientsRealServerTest test flakes
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/ExponentialBackoff.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/OkHttpClients.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/ExponentialBackoffTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/OkHttpClientsRealServerTest.java
Labels: merge when ready, no changelog

#1404 Fix: Remove left over truststore file from http-remoting
  retrofit2-clients/src/test/resources/trustStore.jks
Labels: merge when ready, no changelog

#1401 Improvement: Add method for constructing KeyManager out of SslConfiguration
  keystores/src/main/java/com/palantir/conjure/java/config/ssl/SslSocketFactories.java
Labels: merge when ready, no changelog

#1411 Improvement: Don't require password for keystores constructed from pems
  changelog/@unreleased/pr-1411.v2.yml
  keystores/src/main/java/com/palantir/conjure/java/config/ssl/KeyStores.java
  keystores/src/main/java/com/palantir/conjure/java/config/ssl/SslSocketFactories.java
  keystores/src/test/java/com/palantir/conjure/java/config/ssl/KeyStoresTests.java
Labels: merge when ready

#1406 Improvement: Always include private key parser and provide PKCS#8 support
  .palantir/revapi.yml
  changelog/@unreleased/pr-1406.v2.yml
  keystores/build.gradle
  keystores/src/main/java/com/palantir/conjure/java/config/ssl/KeyStores.java
  keystores/src/main/java/com/palantir/conjure/java/config/ssl/pkcs1/Pkcs1PrivateKeyReader.java
  keystores/src/main/java/com/palantir/conjure/java/config/ssl/pkcs1/Pkcs1Reader.java
  keystores/src/main/java/com/palantir/conjure/java/config/ssl/pkcs1/Pkcs1Readers.java
  keystores/src/test/java/com/palantir/conjure/java/config/ssl/DropwizardSslClientAuthTests.java
  keystores/src/test/java/com/palantir/conjure/java/config/ssl/KeyStoresTests.java
  keystores/src/test/java/com/palantir/conjure/java/config/ssl/SslSocketFactoriesConnectionTests.java
  keystores/src/test/java/com/palantir/conjure/java/config/ssl/SslSocketFactoriesTests.java
  keystores/src/test/java/com/palantir/conjure/java/config/ssl/TestConstants.java
  keystores/src/test/java/com/palantir/conjure/java/config/ssl/pkcs1/Pkcs1ReadersTests.java
  keystores/src/test/java/com/palantir/conjure/java/config/ssl/pkcs1/TestConstants.java
  pkcs1-reader-bouncy-castle/build.gradle
  pkcs1-reader-bouncy-castle/src/main/java/com/palantir/conjure/java/config/ssl/pkcs1/BouncyCastlePkcs1Reader.java
  pkcs1-reader-bouncy-castle/src/main/resources/META-INF/services/com.palantir.conjure.java.config.ssl.pkcs1.Pkcs1Reader
  pkcs1-reader-bouncy-castle/src/test/java/com/palantir/conjure/java/config/ssl/pkcs1/BouncyCastlePkcs1ReaderTests.java
  pkcs1-reader-bouncy-castle/src/test/java/com/palantir/conjure/java/config/ssl/pkcs1/TestConstants.java
  pkcs1-reader-sun/build.gradle
  pkcs1-reader-sun/src/main/java/com/palantir/conjure/java/config/ssl/pkcs1/SunPkcs1Reader.java
  pkcs1-reader-sun/src/main/resources/META-INF/services/com.palantir.conjure.java.config.ssl.pkcs1.Pkcs1Reader
  pkcs1-reader-sun/src/test/java/com/palantir/conjure/java/config/ssl/pkcs1/SunPkcs1ReaderTests.java
  pkcs1-reader-sun/src/test/java/com/palantir/conjure/java/config/ssl/pkcs1/TestConstants.java
  readme.md
  settings.gradle
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#1412 RemotingOkHttpCall logs backoff state prior to retry
  changelog/@unreleased/pr-1412.v2.yml
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/ExponentialBackoff.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpCall.java
Labels: autorelease, merge when ready

#1413 Concurrency limiter listeners are protected against extra calls
  changelog/@unreleased/pr-1413.v2.yml
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/ConcurrencyLimiters.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/ConcurrencyLimitersTest.java
Labels: merge when ready

#1415 fix #1385: Fix a response leak when requests are canceled
  changelog/@unreleased/pr-1415.v2.yml
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/OkHttpClients.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpCall.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/ResponseCapturingInterceptor.java
Labels: autorelease, merge when ready

#1416 Improvement: Move KeepAliveSocketFactory
  changelog/@unreleased/pr-1416.v2.yml
  client-config/src/main/java/com/palantir/conjure/java/client/config/ClientConfigurations.java
  client-config/src/test/java/com/palantir/conjure/java/client/config/ClientConfigurationsTest.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/ForwardingSslSocketFactory.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/KeepAliveSslSocketFactory.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/OkHttpClients.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/KeepAliveSslSocketFactoryTest.java
Labels: autorelease, merge when ready

#1418 Improvement: Support multiple certificates per certificate file
  changelog/@unreleased/pr-1418.v2.yml
  keystores/src/main/java/com/palantir/conjure/java/config/ssl/KeyStores.java
  keystores/src/test/java/com/palantir/conjure/java/config/ssl/KeyStoresTests.java
Labels: autorelease, merge when ready

#1431 Apply concurrency limiting only to network requests
  changelog/@unreleased/pr-1431.v2.yml
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/OkHttpClients.java
Labels: autorelease, merge when ready

#1432 Revert "Apply concurrency limiting only to network requests (#1431)"
  changelog/@unreleased/pr-1432.v2.yml
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/OkHttpClients.java
Labels: autorelease, merge when ready

#1433 run gradlew spotlessApply
  conjure-java-jersey-server/src/test/java/com/palantir/conjure/java/server/jersey/JsonExceptionMapperTest.java
Labels: autorelease, merge when ready, no changelog

#1434 Make JerseyServerMetrics public
  conjure-java-jersey-server/src/main/metrics/jersey-server-metrics.yml
Labels: autorelease, merge when ready, no changelog

#1440 Revert "Make JerseyServerMetrics public"
  .palantir/revapi.yml
  conjure-java-jersey-server/src/main/metrics/jersey-server-metrics.yml
Labels: autorelease, merge when ready, no changelog

#1442 ConjureJerseyFeature.metrics is final
  conjure-java-jersey-server/src/main/java/com/palantir/conjure/java/server/jersey/ConjureJerseyFeature.java
Labels: merge when ready, no changelog

#1443 Update Jersey auth converters to respect nullable annotations
  changelog/@unreleased/pr-1443.v2.yml
  conjure-java-jersey-server/src/main/java/com/palantir/conjure/java/server/jersey/AuthHeaderParamConverterProvider.java
  conjure-java-jersey-server/src/main/java/com/palantir/conjure/java/server/jersey/BearerTokenParamConverterProvider.java
  conjure-java-jersey-server/src/test/java/com/palantir/conjure/java/server/jersey/AuthTest.java
Labels: autorelease, merge when ready

#1441 Indicate endpoint deprecation with a pseudo-standard header
  changelog/@unreleased/pr-1441.v2.yml
  conjure-java-jersey-server/src/main/java/com/palantir/conjure/java/server/jersey/ConjureJerseyFeature.java
  conjure-java-jersey-server/src/main/java/com/palantir/conjure/java/server/jersey/DeprecationReportingResponseFeature.java
  conjure-java-jersey-server/src/test/java/com/palantir/conjure/java/server/jersey/DeprecationTest.java
Labels: merge when ready

#1451 Test connections are shared between clients
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/OkHttpClientsRealServerTest.java
  okhttp-clients/src/test/resources/keyStore.jks
Labels: merge when ready, no changelog

#1452 Fix: Deduplicate certificates deserialized from same security config amongst different clients
  changelog/@unreleased/pr-1452.v2.yml
  keystores/build.gradle
  keystores/src/main/java/com/palantir/conjure/java/config/ssl/KeyStores.java
  keystores/src/test/java/com/palantir/conjure/java/config/ssl/KeyStoresTests.java
Labels: autorelease, merge when ready

#1450 Update the conjure okhttp client connection pool
  changelog/@unreleased/pr-1450.v2.yml
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/OkHttpClients.java
Labels: autorelease, merge when ready

#1445 Http2 requires gcm ciphers to be enabled
  changelog/@unreleased/pr-1445.v2.yml
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/OkHttpClients.java
Labels: autorelease, merge when ready

#1446 Instrument OkHttp client handshakes
  changelog/@unreleased/pr-1446.v2.yml
  okhttp-clients/build.gradle
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/OkHttpClients.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready
