Repository palantir/conjure-java-runtime, pull requests merged in 2021-07, with the labels that each got.

#2022 Replace aged afterburner with the sr71 blackbird module
  changelog/@unreleased/pr-2022.v2.yml
  conjure-java-jackson-serialization/build.gradle
  conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/ObjectMappers.java
  conjure-java-jersey-server/build.gradle
  versions.lock
Labels: autorelease, merge when ready

#2025 Wrap jackson optimization modules with a factory API
  changelog/@unreleased/pr-2025.v2.yml
  conjure-java-jackson-optimizations/build.gradle
  conjure-java-jackson-optimizations/src/main/java/com/palantir/conjure/java/jackson/optimizations/ObjectMapperOptimizations.java
  conjure-java-jackson-serialization/build.gradle
  conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/ObjectMappers.java
  settings.gradle
Labels: autorelease, merge when ready

#2029 Remove jcenter refs from docs+build
  build.gradle
  readme.md
Labels: merge when ready, no changelog

#2031 Switch back to afterburner.
  changelog/@unreleased/pr-2031.v2.yml
  conjure-java-jackson-optimizations/build.gradle
  conjure-java-jackson-optimizations/src/main/java/com/palantir/conjure/java/jackson/optimizations/ObjectMapperOptimizations.java
  versions.lock
Labels: autorelease, merge when ready

#2032 standard jackson dependency pattern
  versions.props
Labels: autorelease, merge when ready, no changelog

#2051 Excavator: Migrate to the logsafe SafeLogger API
  client-config/build.gradle
  client-config/src/main/java/com/palantir/conjure/java/client/config/ClientConfigurations.java
  conjure-java-client-verifier/build.gradle
  conjure-java-client-verifier/src/test/java/com/palantir/verification/VerificationServerRule.java
  conjure-java-jaxrs-client/build.gradle
  conjure-java-jaxrs-client/src/main/java/com/palantir/conjure/java/client/jaxrs/feignimpl/EmptyContainerDecoder.java
  conjure-java-jersey-server/build.gradle
  conjure-java-jersey-server/src/main/java/com/palantir/conjure/java/server/jersey/JsonExceptionMapper.java
  conjure-java-jersey-server/src/main/java/com/palantir/conjure/java/server/jersey/QosExceptionMapper.java
  conjure-java-jersey-server/src/main/java/com/palantir/conjure/java/server/jersey/RemoteExceptionMapper.java
  conjure-java-jersey-server/src/main/java/com/palantir/conjure/java/server/jersey/ServiceExceptionMapper.java
  conjure-java-jersey-server/src/main/java/com/palantir/conjure/java/server/jersey/WebApplicationExceptionMapper.java
  conjure-java-legacy-clients/build.gradle
  conjure-java-legacy-clients/src/main/java/com/palantir/conjure/java/QosExceptionResponseMapper.java
  conjure-java-legacy-clients/src/main/java/com/palantir/conjure/java/okhttp/HostMetricsRegistry.java
  conjure-java-retrofit2-client/build.gradle
  conjure-java-server-verifier/build.gradle
  conjure-java-server-verifier/src/test/java/com/palantir/verification/server/VerificationClientRule.java
  keystores/build.gradle
  keystores/src/main/java/com/palantir/conjure/java/config/ssl/DefaultCas.java
  okhttp-clients/build.gradle
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/ConcurrencyLimiters.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/DeprecationWarningInterceptor.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/LeakDetector.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/OkHttpClients.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemoteExceptionResponseHandler.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpCall.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpClient.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/SpanTerminatingInterceptor.java
  okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/UnknownRemoteExceptionResponseHandler.java
  versions.lock
Labels: autorelease, merge when ready, no changelog
