Repository palantir/conjure-java-runtime, pull requests merged in 2022-08, with the labels that each got.

#2436 conjure-java-jaxrs-client supports javax and jakarta annotations
  changelog/@unreleased/pr-2436.v2.yml
  conjure-java-jaxrs-client/build.gradle
  conjure-java-jaxrs-client/src/main/java/com/palantir/conjure/java/client/jaxrs/AbstractFeignJaxRsClientBuilder.java
  conjure-java-jaxrs-client/src/main/java/com/palantir/conjure/java/client/jaxrs/CompatibleJaxRsContract.java
  conjure-java-jaxrs-client/src/test/java/com/palantir/conjure/java/client/jaxrs/JaxRsClientStackTraceTest.java
  versions.lock
Labels: merge when ready, autorelease

#2437 CompatibleJaxRsContract exceptions retain causal exception
  changelog/@unreleased/pr-2437.v2.yml
  conjure-java-jaxrs-client/src/main/java/com/palantir/conjure/java/client/jaxrs/CompatibleJaxRsContract.java
Labels: merge when ready, autorelease

#2439 Conjure the jersey jackson-feature mapper
  undertow-testing/build.gradle
  undertow-testing/src/main/java/com/palantir/undertest/UndertowServerExtension.java
Labels: no changelog

#2441 Fix conjure-java-jersey-server dependencies
  build.gradle
  conjure-java-client-verifier/build.gradle
  conjure-java-jersey-jakarta-server/build.gradle
  conjure-java-jersey-server/build.gradle
  conjure-java-retrofit2-client/build.gradle
  conjure-java-server-verifier/build.gradle
  gradle/verifier.gradle
  keystores/build.gradle
  okhttp-clients/build.gradle
  versions.lock
  versions.props
Labels: merge when ready, no changelog, autorelease

#2442 Add ForbidJavax Annotation
  changelog/@unreleased/pr-2442.v2.yml
  conjure-java-annotations/src/main/java/com/palantir/errorprone/ForbidJavax.java
Labels: merge when ready, autorelease
