Repository palantir/conjure-java-runtime, pull requests merged in 2023-04, with the labels that each got.

#2580 Upgrade Undertow to 2.2.24.Final
  versions.lock
  versions.props
Labels: merge when ready, no changelog, autorelease

#2583 Disable Jackson field name interning
  changelog/@unreleased/pr-2583.v2.yml
  conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/ObjectMappers.java
Labels: merge when ready, autorelease

#2586 Add public JsonFactory factories to ObjectMappers
  changelog/@unreleased/pr-2586.v2.yml
  conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/InstrumentedJsonFactory.java
  conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/ObjectMappers.java
  conjure-java-jackson-serialization/src/test/java/com/palantir/conjure/java/serialization/ObjectMappersTest.java
Labels: merge when ready, autorelease

#2587 Use a TypeFactory backed by a Caffeine Cache
  changelog/@unreleased/pr-2587.v2.yml
  conjure-java-jackson-serialization/build.gradle
  conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/CaffeineCachingTypeFactory.java
  conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/ObjectMappers.java
  conjure-java-jackson-serialization/src/test/java/com/palantir/conjure/java/serialization/ObjectMappersTest.java
Labels: merge when ready, autorelease

#2588 Add TypeFactory cache instrumentation
  changelog/@unreleased/pr-2588.v2.yml
  conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/CaffeineCachingTypeFactory.java
  conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/ObjectMappers.java
  conjure-java-jackson-serialization/src/main/metrics/jackson-metrics.yml
  conjure-java-jackson-serialization/src/main/metrics/jackson-registry-metrics.yml
  conjure-java-jackson-serialization/src/test/java/com/palantir/conjure/java/serialization/ObjectMappersTest.java
Labels: merge when ready, autorelease

#2595 Opt out of the TypeFactory cache until we can resolve cache contention
  changelog/@unreleased/pr-2595.v2.yml
  conjure-java-jackson-serialization/build.gradle
  conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/CaffeineCachingTypeFactory.java
  conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/NonCachingTypeFactory.java
  conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/ObjectMappers.java
  conjure-java-jackson-serialization/src/main/metrics/jackson-metrics.yml
  conjure-java-jackson-serialization/src/test/java/com/palantir/conjure/java/serialization/ObjectMappersTest.java
Labels: merge when ready, autorelease

#2597 ObjectMappers.withDefaultModules(ObjectMapper) does not replace existing TypeFactories
  changelog/@unreleased/pr-2597.v2.yml
  conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/NonCachingTypeFactory.java
  conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/ObjectMappers.java
  conjure-java-jackson-serialization/src/test/java/com/palantir/conjure/java/serialization/ObjectMappersTest.java
Labels: merge when ready, autorelease

#2601 Apply an excessively permissive large string length limit by default
  changelog/@unreleased/pr-2601.v2.yml
  conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/ObjectMappers.java
  conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/ReflectiveStreamReadConstraints.java
  conjure-java-jackson-serialization/src/test/java/com/palantir/conjure/java/serialization/ObjectMappersTest.java
Labels: merge when ready, autorelease

#2603 Opt out of canonicalization in Conjure JsonFactories
  changelog/@unreleased/pr-2603.v2.yml
  conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/ObjectMappers.java
Labels: merge when ready, autorelease

#2610 SslSocketFactoriesTests checks if Conscrypt is supported
  keystores/src/test/java/com/palantir/conjure/java/config/ssl/SslSocketFactoriesTests.java
Labels: merge when ready, no changelog

#2609 SslSocketFactories avoids duplicate effort creating TLS components
  changelog/@unreleased/pr-2609.v2.yml
  client-config/src/main/java/com/palantir/conjure/java/client/config/ClientConfigurations.java
  keystores/src/main/java/com/palantir/conjure/java/config/ssl/SslSocketFactories.java
Labels: merge when ready, autorelease

#2616 Migrate to junit5
  changelog/@unreleased/pr-2616.v2.yml
  client-config/build.gradle
  client-config/src/test/java/com/palantir/conjure/java/client/config/ClientConfigurationsTest.java
  client-config/src/test/java/com/palantir/conjure/java/clients/ConjureClientsTest.java
  conjure-java-client-verifier/build.gradle
  conjure-java-jackson-serialization/build.gradle
  conjure-java-jackson-serialization/src/test/java/com/palantir/conjure/java/serialization/ObjectMappersTest.java
  conjure-java-jackson-serialization/src/test/java/com/palantir/conjure/java/serialization/ShimJdk7ModuleTest.java
  conjure-java-retrofit2-client/build.gradle
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/AsyncSerializableErrorCallAdapterFactoryTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/OptionalObjectToStringConverterFactoryTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/QosExceptionThrowingCallAdapterFactoryTest.java
  extras/refresh-utils/build.gradle
  extras/refresh-utils/src/test/java/com/palantir/conjure/java/ext/refresh/RefreshableProxyInvocationHandlerTest.java
  extras/refresh-utils/src/test/java/com/palantir/conjure/java/ext/refresh/RefreshableTest.java
  okhttp-clients/build.gradle
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/CatchThrowableInterceptorTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/ConcurrencyLimitersTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/ConcurrencyLimitingInterceptorTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/DefaultConcurrencyLimitersTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/ExponentialBackoffTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/FlowControlTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/HostMetricsRegistryTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/HostMetricsTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/InstrumentedInterceptorTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/KeepAliveSslSocketFactoryTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/LeakDetectorTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/MeshProxyInterceptorTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/OkHttpClientsRealServerTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/OkHttpClientsTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/QosExceptionResponseHandlerTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/RemoteExceptionResponseHandlerTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/ThreadWorkQueueTests.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/UnknownRemoteExceptionResponseHandlerTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/UrlSelectorImplTest.java
  versions.lock
  versions.props
Labels: merge when ready

#2617 Migrate off JUnit 4 vintage
  client-config/build.gradle
  conjure-java-client-verifier/build.gradle
  conjure-java-client-verifier/src/test/java/com/palantir/verification/AutoDeserializeTest.java
  conjure-java-client-verifier/src/test/java/com/palantir/verification/SingleParamServicesTest.java
  conjure-java-client-verifier/src/test/java/com/palantir/verification/VerificationServerRule.java
  conjure-java-jackson-serialization/build.gradle
  conjure-java-jaxrs-client/build.gradle
  conjure-java-jersey-jakarta-server/build.gradle
  conjure-java-retrofit2-client/build.gradle
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2ClientApiTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2ClientBuilderTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2ClientCollectionHandlingTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2ClientConfigRefreshTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2ClientFailoverTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2ClientProxyTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2ClientQueryParamHandlingTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2OptionalBinaryHandlingTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/TracerTest.java
  conjure-java-server-verifier/build.gradle
  extras/refresh-utils/build.gradle
  keystores/build.gradle
  okhttp-clients/build.gradle
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/OkHttpClientsTest.java
  okhttp-clients/src/test/java/com/palantir/conjure/java/okhttp/UserAgentInterceptorTest.java
  versions.lock
  versions.props
Labels: merge when ready, no changelog
