Repository palantir/conjure-java-runtime, pull requests merged in 2023-12, with the labels that each got.

#1853 Break: Remove Retrofit Support
  build.gradle
  changelog/@unreleased/pr-1853.v2.yml
  conjure-java-client-verifier/build.gradle
  conjure-java-client-verifier/src/generatedRetrofit/java/.gitignore
  conjure-java-client-verifier/src/test/java/com/palantir/verification/AutoDeserializeTest.java
  conjure-java-client-verifier/src/test/java/com/palantir/verification/Cases.java
  conjure-java-client-verifier/src/test/java/com/palantir/verification/VerificationClients.java
  conjure-java-client-verifier/src/test/resources/ignored-test-cases.retrofit.yml
  conjure-java-retrofit2-client/build.gradle
  conjure-java-retrofit2-client/src/main/java/com/palantir/conjure/java/client/retrofit2/AsyncSerializableErrorCallAdapterFactory.java
  conjure-java-retrofit2-client/src/main/java/com/palantir/conjure/java/client/retrofit2/CborConverterFactory.java
  conjure-java-retrofit2-client/src/main/java/com/palantir/conjure/java/client/retrofit2/CoerceNullValuesCallAdapterFactory.java
  conjure-java-retrofit2-client/src/main/java/com/palantir/conjure/java/client/retrofit2/CoerceNullValuesConverterFactory.java
  conjure-java-retrofit2-client/src/main/java/com/palantir/conjure/java/client/retrofit2/NeverReturnNullConverterFactory.java
  conjure-java-retrofit2-client/src/main/java/com/palantir/conjure/java/client/retrofit2/OptionalObjectToStringConverterFactory.java
  conjure-java-retrofit2-client/src/main/java/com/palantir/conjure/java/client/retrofit2/OptionalResponseBodyConverterFactory.java
  conjure-java-retrofit2-client/src/main/java/com/palantir/conjure/java/client/retrofit2/QosExceptionThrowingCallAdapterFactory.java
  conjure-java-retrofit2-client/src/main/java/com/palantir/conjure/java/client/retrofit2/Retrofit2Client.java
  conjure-java-retrofit2-client/src/main/java/com/palantir/conjure/java/client/retrofit2/Retrofit2ClientBuilder.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/AsyncSerializableErrorCallAdapterFactoryTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/OptionalObjectToStringConverterFactoryTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/QosExceptionThrowingCallAdapterFactoryTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2ClientApiTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2ClientBuilderTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2ClientCollectionHandlingTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2ClientConfigRefreshTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2ClientFailoverTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2ClientProxyTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2ClientQueryParamHandlingTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/Retrofit2OptionalBinaryHandlingTest.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/TestBase.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/TestService.java
  conjure-java-retrofit2-client/src/test/java/com/palantir/conjure/java/client/retrofit2/TracerTest.java
  conjure-java-retrofit2-client/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  conjure-java-retrofit2-client/src/test/resources/trustStore.jks
  conjure-java-server-verifier/build.gradle
  conjure-java-server-verifier/src/generatedRetrofit/java/.gitignore
  gradle/verifier.gradle
  readme.md
  settings.gradle
  versions.lock
  versions.props
Labels: merge when ready, autorelease, long-lived, 🤖 fix nits

#2742 fix changelog
  changelog/@unreleased/pr-1853.v2.yml
Labels: merge when ready

#2755 Downgrade Jackson to 2.15.3
  build.gradle
  versions.lock
  versions.props
Labels: merge when ready, no changelog, autorelease

#2744 Clean up version constraints
  versions.lock
  versions.props
Labels: merge when ready, no changelog
